		</div>
		<div id="license">
		  <a rel="license" href="<?= WEBROOT ?>about.html#license"><img src="<?= WEBROOT ?>images/by-nc.png" height="15" width="30" align="absbottom" /></a>
		</div>
	</div>
</body>

<!-- Google Analytics stuff -->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
<script type="text/javascript">
	_uacct = "UA-432885-1";
	urchinTracker();
</script>
<!-- Done! -->

</html>